### ISSUE TITLE
fails to save on 3.7.1

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-qtype_pmatchjme#16]
Moodle 3.7.1
The JSME Molecular Editor shows up OK, and allows drawing the answer structure, but upon submitting the answer, the attempt isn't saved.

**Comment by aspark21** [comment]
Noted so far in chrome console:

Warning: the global function "jsmeOnLoad" is not defined.
 If you have defined it, there might be a syntax error in your javascript code.

possibly unrelated

**Comment by timhunt** [comment]
Ah! it is one of those breakages. Well done for working this out.

**Comment by timhunt** [comment]
Fixed by sugunb's pull request.
