### ISSUE TITLE
Fatal error: incompatible class method

### ISSUE THREAD

**Issue by thepurpleblob** [moodleou/moodle-qtype_pmatchjme#23]
Full error...

Fatal error: Declaration of qtype_pmatchjme::delete_question($questionid, $contextid) must be compatible with qtype_pmatch::delete_question($questionid, $contextid): void in /blah/blah/question/type/pmatchjme/questiontype.php on line 114

pmatchjme is version

$plugin->version   = 2020090800;

line in question is...

public function delete_question($questionid, $context) {

pmatch version...

$plugin->version   = 2022080900;

line in question is 

public function delete_question($questionid, $contextid): void {

**Comment by timhunt** [comment]
Yes. We are working on it.

If you want a quick fix, add the required : void in qtype_pmatchjme to make it match.

**Comment by universityofglasgow** [comment]
I did :)

**Comment by timhunt** [comment]
I will close this issue, since it will be fixed as part of a more general check that everything is workin in 4.0.
